import Head from 'next/head'
import Image from 'next/image'
import Fleet from '../components/Fleet'
import KeyPoint from '../components/KeyPoint'
import Nav from '../components/Nav'
import Header from '../components/Header'
import KeyPoints from '../components/KeyPoints'
import Footer from '../components/Footer'

export default function Home() {
	return (
		<div className='bg-[#001951]'>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Nav />
			<Header />
			<KeyPoints />
			<Fleet />
			<Footer />

			{/* Header */}
			{/* <Header /> */}


			{/* Locations */}

			{/* About */}

			{/* Fleet */}

			{/* Testimonials */}

			{/* Footer */}

		</div>
	)
}
